- yum: pkg=nginx state=present

- file: path=/etc/nginx/conf.d/default.conf state=absent

- service: name=nginx enabled=yes

- copy: src=app.conf dest=/etc/nginx/conf.d/app.conf owner=root group=root
  notify:
    - restart nginx
