- yum: pkg=nginx state=present
  sudo: yes

- service: name=nginx enabled=yes
  sudo: yes
  notify:
    - restart nginx

- file: path=/etc/nginx/conf.d/default.conf state=absent
  sudo: yes
  notify:
    - restart nginx

- copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  sudo: yes
  notify:
    - restart nginx

- template: src=app.conf dest=/etc/nginx/conf.d/app.conf
  sudo: yes
  notify:
    - restart nginx
