- yum: pkg=nginx state=present
  sudo: yes

- name: remove default.conf
  file: path=/etc/nginx/conf.d/default.conf state=absent
  notify:
    - restart nginx
  sudo: yes

- name: copy nginx.conf
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx
  sudo: yes

- name: create a directory for ssl certs
  file: path=/etc/nginx/ssl state=directory mode=0600
  when: ssl_cert != False
  sudo: yes

- name: copy ssl certificates
  copy: src={{ ssl_cert }}.{{ item }} dest=/etc/nginx/ssl/{{ ssl_cert }}.{{ item }} mode=0600
  with_items: [ key, pem ]
  when: ssl_cert != False
  notify:
    - restart nginx
  sudo: yes

- name: copy application.conf
  template: src=unicorn.conf dest=/etc/nginx/conf.d/{{ deploy_user }}.conf
  notify:
    - restart nginx
  sudo: yes

- service: name=nginx enabled=yes state=started
  sudo: yes
