- local_action: command date +%s
  register: timestamp

- file: path={{ item }} state=directory recurse=yes mode=755
  with_items:
    - "{{ deploy_root }}"
    - "{{ deploy_releases_path }}"
    - "{{ deploy_shared_path }}"

- file: path="{{ deploy_releases_path }}/{{ timestamp.stdout }}" state=directory mode=701
  register: deploy_release

- git: repo={{ deploy_repo }} version={{ deploy_version }} dest={{deploy_release.path }} update=yes depth=1

- template: src=unicorn/unicorn.conf.rb dest="{{ deploy_release.path }}/unicorn.conf.rb"

- shell: chdir={{ deploy_release.path }} {{ item }}
  with_items: deploy_cmds
  environment: env
  notify:
    - rbenv rehash

- file: path={{ deploy_current_release_path }} src={{ deploy_release.path }} state=link
  environment: env
  notify:
    - restart unicorn

- name: copy {{ application_name }}.conf
  template: src=nginx/unicorn.conf dest=/etc/nginx/conf.d/{{ application_name }}.conf
  notify:
    - restart nginx
  sudo: yes
