#!/bin/bash

export HOME=$(su --login {{ deploy_user }} --command='echo "$HOME"')
{% for var, value in env.iteritems() %}
export {{ var }}="{{ value }}"
{% endfor %}

exec 2>&1
exec chpst -u {{ deploy_user }} \
  $HOME/.rbenv/shims/unicorn \
    -c {{ deploy_current_release_path }}/unicorn.conf.rb \
    {{ deploy_current_release_path }}/config.ru
