- local_action: command date +%s
  register: timestamp

- file: path={{ item }} state=directory
  with_items:
    - "{{ deploy_root }}"
    - "{{ releases_path }}"

- file: path="{{ releases_path }}/{{ timestamp.stdout }}" state=directory
  register: release_path

- copy: src=Gemfile dest={{ release_path.path }}/Gemfile
- copy: src=Gemfile.lock dest={{ release_path.path }}/Gemfile.lock
- copy: src=config.ru dest={{ release_path.path }}/config.ru

- template: src=unicorn.conf.rb dest={{ release_path.path }}/unicorn.conf.rb

- shell: chdir={{ release_path.path }} {{ item }}
  with_items: deploy_cmds

- file: path={{ current_path }} src={{ release_path.path }} state=link
  notify:
    - rbenv rehash
    - restart unicorn
