- hosts: all
  sudo: no
  roles:
    - deploy
  vars:
    packages:
      - fail2ban
      - git
      - ncdu
      - vim
      - htop

    iptables:
      - { protocol: tcp, port: 22 }
      - { protocol: tcp, port: 80 }

    ruby_version:   2.0.0-p353

    deploy_version: master
    deploy_repo:    https://github.com/jamesmoriarty/rackup.git
    deploy_cmds:
      - "gem install bundler"
      - "bundle install"
