- hosts: all
  sudo: no
  roles:
    - common
    - deploy
  vars_files:
    - vars/main.yml
  vars:
    ruby_version:   2.0.0-p353

    deploy_version: master
    deploy_repo:    https://github.com/jamesmoriarty/rackup.git
    deploy_cmds:
      - "gem install bundler"
      - "bundle install"
