---
- name: all
  hosts: all
  vars:
    ruby_version:   2.0.0-p353
    deploy_root:    "~/app"
    releases_path:  "{{ deploy_root }}/releases"
    current_path:  "{{ deploy_root }}/current"
  roles:
    - selinux
    - app
