---
- name: all
  hosts: all
  sudo: no
  vars:
    ruby_version:   2.0.0-p353

    deploy_root:    "~/app"
    releases_path:  "{{ deploy_root }}/releases"
    current_path:   "{{ deploy_root }}/current"

    unicorn_socket_path: "/tmp/unicorn.socket"
    unicorn_log_path:    "/tmp/unicorn.log"
    unicorn_pid_path:    "/tmp/unicorn.pid"
  roles:
    - selinux
    - rack_app
