- hosts: all
  sudo: no
  roles:
    - common
  vars:
    common_packages:
      - git
      - ncdu
      - vim
      - htop
      - libpqxx-devel

- hosts: db
  sudo: no
  roles:
    - postgresql

- hosts: app
  sudo: no
  vars_files:
    - vars/main.yml
  vars:
    ruby_version:   2.0.0-p353
    rackup_version: f54da8e38e7d03838bb3421578aa0a6dd6465f9f
    rackup_repo:    https://github.com/jamesmoriarty/simple-sinatra-sequel-blog.git
    rackup_cmds:
      - 'psql -U postgres {{ db }} --command="SELECT version();" >/dev/null 2>&1 || createdb -U postgres {{ db }}'
      - "gem list bundler -i | grep true || gem install bundler"
      - "bundle config build.pg --with-pg=/usr/pgsql-9.3"
      - "bundle"
    db: blog
    env:
      DATABASE_URL: "postgres://postgres@127.0.0.1/{{ db }}"
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: password
  roles:
    - rackup
