---
- name: all
  hosts: all
  sudo: no
  vars_files:
    - vars/main.yml
  vars:
    ruby_version:   2.0.0-p353

    deploy_cmds: [
      "gem list bundler -i | grep true || gem install bundler",
      "bundle"
    ]
  roles:
    - common
    - rack_app
