- hosts: all
  sudo: no
  roles:
    - common
  vars:
    common_packages:
      - git
      - ncdu
      - vim
      - htop

- hosts: db
  sudo: no
  roles:
    - postgresql

- hosts: app
  sudo: no
  vars_files:
    - vars/main.yml
  vars:
    dbuser: "postgres"
    dbname: "blog"
    dbhost: "{{ hostvars[groups['db'][0]].ansible_all_ipv4_addresses[-1] }}"

    common_packages:
      - libpqxx-devel

    ruby_version:   2.0.0-p353

    rackup_version: f54da8e38e7d03838bb3421578aa0a6dd6465f9f
    rackup_repo:    https://github.com/jamesmoriarty/simple-sinatra-sequel-blog.git
    rackup_cmds:
      - 'psql --host={{ dbhost }} --username={{ dbuser }} {{ dbname }} --command="SELECT version();" >/dev/null 2>&1 || createdb --host={{ dbhost }} --username={{ dbuser }} {{ dbname }}'
      - "gem list bundler -i | grep true || gem install bundler"
      - "bundle config build.pg --with-pg=/usr/pgsql-9.3"
      - "bundle"

    env:
      DATABASE_URL: "postgres://{{ dbuser }}@{{ dbhost }}/{{ dbname }}"
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: password
  roles:
    - common
    - rackup
