- name: create service directory
  file: path=/etc/service/{{ application_name }} recurse=yes state=directory owner={{ deploy_user }} group={{ deploy_user }}
  sudo: yes

- name: create service run script
  template: src=runit/run dest=/etc/service/{{ application_name }}/run mode=0755 owner={{ deploy_user }} group={{ deploy_user }}
  sudo: yes

- name: wait for runit supervision
  wait_for: path=/etc/service/{{ application_name }}/supervise/{{ item }}
  with_items:
    - control
  sudo: yes

- name: change service control directory owner
  file: path=/etc/service/{{ application_name }}/supervise recurse=yes owner={{ deploy_user }} group={{ deploy_user }}
  ignore_errors: yes
  sudo: yes
