- name: check unicorn installed
  shell: gem list unicorn -i | grep true
  register: unicorn_installed
  ignore_errors: yes

- shell: gem install unicorn
  when: unicorn_installed|failed
  notify:
    - rbenv rehash
