# START COPY APP

- file: path=~/app state=directory
  sudo: no

- copy: src=app/Gemfile dest=~/app/Gemfile
  sudo: no

- copy: src=app/Gemfile.lock dest=~/app/Gemfile.lock
  sudo: no

- copy: src=app/config.ru dest=~/app/config.ru
  sudo: no

- copy: src=app/unicorn.conf.rb dest=~/app/unicorn.conf.rb
  sudo: no

# END COPY APP

# BEFORE RESTART

- name: gem install bundler
  action: shell gem install bundler
  sudo: no

- name: bundle
  action: shell chdir=~/app bundle
  sudo: no
  notify:
    - rbenv rehash

# END RESTART

- name: ensure unicorn running
  raw: "kill -0 $(cat /tmp/app.unicorn.pid)"
  sudo: no
  register: result
  ignore_errors: yes

- name: restart unicorn
  raw: "kill -HUP $(cat /tmp/app.unicorn.pid)"
  sudo: no
  when: result|success

- name: start unicorn
  shell: chdir=~/app unicorn -D -c unicorn.conf.rb config.ru
  sudo: no
  when: result|failed
