- local_action: command date +%s
  register: timestamp

- file: path={{ item }} state=directory
  with_items:
    - "{{ deploy_root }}"
    - "{{ releases_path }}"

- file: path="{{ releases_path }}/{{ timestamp.stdout }}" state=directory
  register: release_path

- git: repo={{ rackup_repo }} version={{ rackup_version }} dest={{ release_path.path }}

- template: src=unicorn.conf.rb dest="{{ release_path.path }}/unicorn.conf.rb"

- shell: chdir={{ release_path.path }} {{ item }}
  with_items: rackup_cmds
  environment: env
  notify:
    - rbenv rehash

- file: path={{ current_path }} src={{ release_path.path }} state=link
  environment: env
  notify:
    - restart unicorn
