- name: install libselinux-python
  yum: pkg=libselinux-python state=installed
  sudo: yes

- name: install tools
  yum: name={{ item }} state=present
  with_items:
    - git
    - ncdu
    - vim
    - htop
  sudo: yes

- name: disable selinux
  selinux: state=disabled
  sudo: yes
