- yum: pkg=libselinux-python state=installed
  sudo: yes

- yum: name={{ item }} state=present
  with_items: common_packages
  sudo: yes

- selinux: state=disabled
  sudo: yes

- name: add known host
  shell: ssh-keyscan -t rsa,dsa {{ item }} 2>&1 | sort -u - ~/.ssh/known_hosts > ~/.ssh/known_hosts
  with_items:
    - github.com
