- name: up unicorn
  command: /sbin/sv up app

- name: start unicorn
  command: /sbin/sv start app

- name: reload unicorn
  command: /sbin/sv 1 app

- name: stop unicorn
  command: /sbin/sv stop app
