- name: rbenv | install build depends
  yum: pkg={{ item }} state=present
  with_items:
    - gcc
    - gcc-c++
    - make
    - automake
    - autoconf
    - curl-devel
    - openssl-devel
    - zlib-devel
    - httpd-devel
    - apr-devel
    - apr-util-devel
    - sqlite-devel

- name: rbenv | create group
  group: name=rbenv

- name: rbenv | add current user
  user: name=vagrant groups=rbenv append=true

- name: rbenv | update rbenv repo
  git: repo=git://github.com/sstephenson/rbenv.git dest=/usr/local/rbenv version=v0.4.0

- name: rbenv | add rbenv to path
  file: path=/usr/local/bin/rbenv src=/usr/local/rbenv/bin/rbenv state=link

- name: rbenv | add rbenv initialization to profile
  copy: src=rbenv.sh dest=/etc/profile.d/rbenv.sh owner=root group=rbenv mode=2755

- name: rbenv | check ruby-build installed
  command: test -x /usr/local/bin/ruby-build
  register: rbuild_present
  ignore_errors: yes

- name: rbenv | create temporary directory
  command: mktemp -d
  register: tempdir
  when: rbuild_present|failed

- name: rbenv | clone ruby-build repo
  git: repo=git://github.com/sstephenson/ruby-build.git dest={{tempdir.stdout}}/ruby-build
  when: rbuild_present|failed

- name: rbenv | install ruby-build
  command: ./install.sh chdir={{tempdir.stdout}}/ruby-build
  when: rbuild_present|failed

- name: rbenv | remove temporary directory
  file: path={{tempdir.stdout}} state=absent
  when: rbuild_present|failed

- file: path=/usr/local/rbenv/{{ item }} state=directory
  with_items:
    - shims
    - versions

# TODO - pending https://github.com/sstephenson/ruby-build/issues/400
- file: path=/usr/local/rbenv recurse=yes group=rbenv mode=777  #2775
  when: rbuild_present|failed
