- name: install build depends
  yum: pkg={{ item }} state=present
  sudo: yes
  with_items:
    - apr-devel
    - apr-util-devel
    - autoconf
    - automake
    - curl-devel
    - gcc
    - gcc-c++
    - glibc-headers
    - httpd-devel
    - libyaml-devel
    - make
    - openssl-devel
    - readline
    - readline-devel
    - sqlite-devel
    - zlib
    - zlib-devel

- name: clone rbenv repo
  git: depth=1 update=no repo=git://github.com/sstephenson/rbenv.git dest=.rbenv version=v0.4.0

- name: add rbenv initialization to profile
  copy: src=rbenv.sh dest=/etc/profile.d/rbenv.sh
  sudo: yes
