- name: rbenv | check ruby ruby_version installed
  shell: rbenv versions | grep {{ruby_version}}
  register: ruby_installed
  ignore_errors: yes

- name: rbenv | install ruby ruby_version
  shell: rbenv install {{ruby_version}}
  when: ruby_installed|failed

- name: rbenv | set global ruby {{ruby_version}}
  shell: rbenv global {{ruby_version}}
  notify:
    - rbenv rehash
