---
application_name:             "app"

deploy_user:                  "{{ ansible_ssh_user }}"
deploy_root:                  "~/{{ application_name }}"
deploy_releases_path:         "{{ deploy_root }}/releases"
deploy_current_release_path:  "{{ deploy_root }}/current"
deploy_shared_path:           "{{ deploy_root }}/shared"

unicorn_socket_path: "/tmp/{{ application_name }}.socket"
unicorn_log_path:    "/tmp/{{ application_name }}.log"
unicorn_pid_path:    "/tmp/{{ application_name }}.pid"
